export const LOADING_DATA = 'LOADING_DATA'
export const CLEAR_LOADING_DATA = 'CLEAR_LOADING_DATA'
export const GET_ERRORS = 'GET_ERRORS'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
